// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package httpapi

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for JobStatus.
const (
	Canceled  JobStatus = "canceled"
	Failed    JobStatus = "failed"
	Queued    JobStatus = "queued"
	Running   JobStatus = "running"
	Succeeded JobStatus = "succeeded"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// JobDetails defines model for JobDetails.
type JobDetails struct {
	Attempt         int             `json:"attempt"`
	ErrorMessage    *string         `json:"error_message,omitempty"`
	FinishedAt      *time.Time      `json:"finished_at,omitempty"`
	LastHeartbeatAt *time.Time      `json:"last_heartbeat_at,omitempty"`
	OutputFiles     []OutputFileRef `json:"output_files"`
	SimulateFailure *bool           `json:"simulate_failure,omitempty"`
	SourceRef       string          `json:"source_ref"`
	StartedAt       *time.Time      `json:"started_at,omitempty"`
	Summary         JobSummary      `json:"summary"`
}

// JobResultURL defines model for JobResultURL.
type JobResultURL struct {
	ExpiresAt time.Time `json:"expires_at"`
	FileName  string    `json:"file_name"`
	Key       string    `json:"key"`
	Url       string    `json:"url"`
}

// JobResultURLsResponse defines model for JobResultURLsResponse.
type JobResultURLsResponse struct {
	Items []JobResultURL `json:"items"`
}

// JobStatus defines model for JobStatus.
type JobStatus string

// JobSummary defines model for JobSummary.
type JobSummary struct {
	CreatedAt       time.Time `json:"created_at"`
	CurrentStep     *string   `json:"current_step,omitempty"`
	IdempotencyKey  *string   `json:"idempotency_key,omitempty"`
	JobId           string    `json:"job_id"`
	ProgressPercent *int      `json:"progress_percent,omitempty"`
	Status          JobStatus `json:"status"`
	UpdatedAt       time.Time `json:"updated_at"`
}

// ListJobsResponse defines model for ListJobsResponse.
type ListJobsResponse struct {
	Items []JobSummary `json:"items"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	AccessToken string `json:"access_token"`
	ExpiresIn   int    `json:"expires_in"`
	TokenType   string `json:"token_type"`
}

// OutputFileRef defines model for OutputFileRef.
type OutputFileRef struct {
	FileName  string `json:"file_name"`
	Key       string `json:"key"`
	SizeBytes *int   `json:"size_bytes,omitempty"`
}

// ListJobsParams defines parameters for ListJobs.
type ListJobsParams struct {
	Limit  *int       `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int       `form:"offset,omitempty" json:"offset,omitempty"`
	Status *JobStatus `form:"status,omitempty" json:"status,omitempty"`
}

// GetJobResultUrlsParams defines parameters for GetJobResultUrls.
type GetJobResultUrlsParams struct {
	TtlSeconds *int `form:"ttl_seconds,omitempty" json:"ttl_seconds,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /healthz)
	Healthz(c *gin.Context)

	// (POST /v1/auth/login)
	Login(c *gin.Context)

	// (GET /v1/jobs)
	ListJobs(c *gin.Context, params ListJobsParams)

	// (GET /v1/jobs/{job_id})
	GetJob(c *gin.Context, jobId string)

	// (GET /v1/jobs/{job_id}/result-urls)
	GetJobResultUrls(c *gin.Context, jobId string, params GetJobResultUrlsParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Healthz(c)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// ListJobs operation middleware
func (siw *ServerInterfaceWrapper) ListJobs(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListJobsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", c.Request.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListJobs(c, params)
}

// GetJob operation middleware
func (siw *ServerInterfaceWrapper) GetJob(c *gin.Context) {

	var err error

	// ------------- Path parameter "job_id" -------------
	var jobId string

	err = runtime.BindStyledParameterWithOptions("simple", "job_id", c.Param("job_id"), &jobId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter job_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetJob(c, jobId)
}

// GetJobResultUrls operation middleware
func (siw *ServerInterfaceWrapper) GetJobResultUrls(c *gin.Context) {

	var err error

	// ------------- Path parameter "job_id" -------------
	var jobId string

	err = runtime.BindStyledParameterWithOptions("simple", "job_id", c.Param("job_id"), &jobId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter job_id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetJobResultUrlsParams

	// ------------- Optional query parameter "ttl_seconds" -------------

	err = runtime.BindQueryParameter("form", true, false, "ttl_seconds", c.Request.URL.Query(), &params.TtlSeconds)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ttl_seconds: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetJobResultUrls(c, jobId, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.Healthz)
	router.POST(options.BaseURL+"/v1/auth/login", wrapper.Login)
	router.GET(options.BaseURL+"/v1/jobs", wrapper.ListJobs)
	router.GET(options.BaseURL+"/v1/jobs/:job_id", wrapper.GetJob)
	router.GET(options.BaseURL+"/v1/jobs/:job_id/result-urls", wrapper.GetJobResultUrls)
}
