// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package httpapi

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for JobStatus.
const (
	Cancelled  JobStatus = "cancelled"
	Done       JobStatus = "done"
	Failed     JobStatus = "failed"
	InProgress JobStatus = "in_progress"
	New        JobStatus = "new"
	Queued     JobStatus = "queued"
)

// Defines values for LoginResponseTokenType.
const (
	Bearer LoginResponseTokenType = "Bearer"
)

// AuthUser defines model for AuthUser.
type AuthUser struct {
	Email  string `json:"email"`
	UserId string `json:"user_id"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Mode   string `json:"mode"`
	Status string `json:"status"`
}

// JobDetails defines model for JobDetails.
type JobDetails struct {
	Attempt         int             `json:"attempt"`
	ErrorMessage    *string         `json:"error_message"`
	FinishedAt      *time.Time      `json:"finished_at"`
	LastHeartbeatAt *time.Time      `json:"last_heartbeat_at"`
	OutputFiles     []OutputFileRef `json:"output_files"`
	SimulateFailure bool            `json:"simulate_failure"`
	SourceRef       *string         `json:"source_ref"`
	StartedAt       *time.Time      `json:"started_at"`
	Summary         JobSummary      `json:"summary"`
}

// JobMutationResponse defines model for JobMutationResponse.
type JobMutationResponse struct {
	Job JobDetails `json:"job"`
}

// JobResultURLsResponse defines model for JobResultURLsResponse.
type JobResultURLsResponse struct {
	Items []ResultFileURL `json:"items"`
}

// JobStatus defines model for JobStatus.
type JobStatus string

// JobSummary defines model for JobSummary.
type JobSummary struct {
	CreatedAt       time.Time `json:"created_at"`
	CurrentStep     *string   `json:"current_step"`
	IdempotencyKey  *string   `json:"idempotency_key"`
	JobId           string    `json:"job_id"`
	ProgressPercent int       `json:"progress_percent"`
	Status          JobStatus `json:"status"`
	UpdatedAt       time.Time `json:"updated_at"`
}

// ListJobsResponse defines model for ListJobsResponse.
type ListJobsResponse struct {
	Items []JobSummary `json:"items"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	AccessToken string                 `json:"access_token"`
	TokenType   LoginResponseTokenType `json:"token_type"`
	User        AuthUser               `json:"user"`
}

// LoginResponseTokenType defines model for LoginResponse.TokenType.
type LoginResponseTokenType string

// OutputFileRef defines model for OutputFileRef.
type OutputFileRef struct {
	FileName  string `json:"file_name"`
	Key       string `json:"key"`
	SizeBytes *int   `json:"size_bytes"`
}

// ResultFileURL defines model for ResultFileURL.
type ResultFileURL struct {
	ExpiresAt time.Time `json:"expires_at"`
	FileName  string    `json:"file_name"`
	Key       string    `json:"key"`
	Url       string    `json:"url"`
}

// SubmitJobRequest defines model for SubmitJobRequest.
type SubmitJobRequest struct {
	IdempotencyKey  string  `json:"idempotency_key"`
	Name            *string `json:"name"`
	SimulateFailure *bool   `json:"simulate_failure,omitempty"`
	SourceRef       *string `json:"source_ref"`
}

// SubmitJobResponse defines model for SubmitJobResponse.
type SubmitJobResponse struct {
	Created bool       `json:"created"`
	Job     JobDetails `json:"job"`
}

// ListJobsParams defines parameters for ListJobs.
type ListJobsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetJobResultUrlsParams defines parameters for GetJobResultUrls.
type GetJobResultUrlsParams struct {
	TtlSeconds *int `form:"ttl_seconds,omitempty" json:"ttl_seconds,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// SubmitJobJSONRequestBody defines body for SubmitJob for application/json ContentType.
type SubmitJobJSONRequestBody = SubmitJobRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Health check
	// (GET /healthz)
	Healthz(c *gin.Context)
	// Username/password login (standalone)
	// (POST /v1/auth/login)
	Login(c *gin.Context)
	// List current user jobs
	// (GET /v1/jobs)
	ListJobs(c *gin.Context, params ListJobsParams)
	// Submit a reconstruction job asynchronously (idempotent by idempotency_key)
	// (POST /v1/jobs)
	SubmitJob(c *gin.Context)
	// Get details for a single job
	// (GET /v1/jobs/{job_id})
	GetJob(c *gin.Context, jobId string)
	// Cancel a queued/running job
	// (POST /v1/jobs/{job_id}/cancel)
	CancelJob(c *gin.Context, jobId string)
	// Resolve result file URLs for a job
	// (GET /v1/jobs/{job_id}/result-urls)
	GetJobResultUrls(c *gin.Context, jobId string, params GetJobResultUrlsParams)
	// Retry a failed/cancelled job
	// (POST /v1/jobs/{job_id}/retry)
	RetryJob(c *gin.Context, jobId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Healthz(c)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// ListJobs operation middleware
func (siw *ServerInterfaceWrapper) ListJobs(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListJobsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListJobs(c, params)
}

// SubmitJob operation middleware
func (siw *ServerInterfaceWrapper) SubmitJob(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SubmitJob(c)
}

// GetJob operation middleware
func (siw *ServerInterfaceWrapper) GetJob(c *gin.Context) {

	var err error

	// ------------- Path parameter "job_id" -------------
	var jobId string

	err = runtime.BindStyledParameterWithOptions("simple", "job_id", c.Param("job_id"), &jobId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter job_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetJob(c, jobId)
}

// CancelJob operation middleware
func (siw *ServerInterfaceWrapper) CancelJob(c *gin.Context) {

	var err error

	// ------------- Path parameter "job_id" -------------
	var jobId string

	err = runtime.BindStyledParameterWithOptions("simple", "job_id", c.Param("job_id"), &jobId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter job_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CancelJob(c, jobId)
}

// GetJobResultUrls operation middleware
func (siw *ServerInterfaceWrapper) GetJobResultUrls(c *gin.Context) {

	var err error

	// ------------- Path parameter "job_id" -------------
	var jobId string

	err = runtime.BindStyledParameterWithOptions("simple", "job_id", c.Param("job_id"), &jobId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter job_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetJobResultUrlsParams

	// ------------- Optional query parameter "ttl_seconds" -------------

	err = runtime.BindQueryParameter("form", true, false, "ttl_seconds", c.Request.URL.Query(), &params.TtlSeconds)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ttl_seconds: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetJobResultUrls(c, jobId, params)
}

// RetryJob operation middleware
func (siw *ServerInterfaceWrapper) RetryJob(c *gin.Context) {

	var err error

	// ------------- Path parameter "job_id" -------------
	var jobId string

	err = runtime.BindStyledParameterWithOptions("simple", "job_id", c.Param("job_id"), &jobId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter job_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RetryJob(c, jobId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.Healthz)
	router.POST(options.BaseURL+"/v1/auth/login", wrapper.Login)
	router.GET(options.BaseURL+"/v1/jobs", wrapper.ListJobs)
	router.POST(options.BaseURL+"/v1/jobs", wrapper.SubmitJob)
	router.GET(options.BaseURL+"/v1/jobs/:job_id", wrapper.GetJob)
	router.POST(options.BaseURL+"/v1/jobs/:job_id/cancel", wrapper.CancelJob)
	router.GET(options.BaseURL+"/v1/jobs/:job_id/result-urls", wrapper.GetJobResultUrls)
	router.POST(options.BaseURL+"/v1/jobs/:job_id/retry", wrapper.RetryJob)
}
